# Generated by Django 3.2.7 on 2021-09-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product_category',
            field=models.CharField(choices=[('Commercial', 'Commercial'), ('Helicopter', 'Helicopter'), ('Space', 'Space')], max_length=100),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product_description',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='units',
            field=models.IntegerField(default=0),
        ),
    ]
