# Generated by Django 3.2.7 on 2021-09-28 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20210927_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='product_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
